### ISSUE TITLE
Toggle multiple times error 

### ISSUE THREAD

**Issue by madsid** [maruthip25/css-switch#1]
While toggling from one css file to other 2nd time it does not change css until you click again. 

```HTML
 <div class="test" id="test" style="width:30px;"> </div>
	<div class="rocker"></div>

	<script type="text/javascript" charset="utf-8">
		initSwitch("style1.css","style2.css","#test");	
	</script>
```

**Comment by maruthip25** [comment]
This issue is being caused because of including both the css files in the head tag as opposed to the intended usage of only the "offcss" file in the head tag. However, this is addressed in new v0.1 where it's no longer necessary to include either of the two css files as the script itself adds the "offcss" file - by default to the head tag.
